CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    birthdate DATE,
    birthplace VARCHAR(255),
    sex VARCHAR(255),
    address VARCHAR(255)
);
